// src/app/settings/settings-header/settings-header.component.ts
/**
 * @license BSD-3-Clause
 * Copyright (c) 2021, ッツ Reader Authors
 * All rights reserved.
 */

import { trigger } from '@angular/animations';
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';
import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons';
import { iconInOut } from 'src/app/utils/header-animations';

@Component({
  selector: 'app-settings-header',
  templateUrl: './settings-header.component.html',
  styleUrls: ['./settings-header.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [trigger('iconInOut', iconInOut)],
})
export class SettingsHeaderComponent {
  @Input()
  leavePageLink = '/manage';

  faSignOutAlt = faSignOutAlt;
}

<div class="relative h-12 xl:h-10 bg-gray-700 text-white">
  <div class="flex justify-end h-full px-screen">
    <div class="flex transform-gpu translate-x-header-fa">
      <a [routerLink]="leavePageLink" [@iconInOut]>
        <fa-icon class="flex items-center h-full text-xl xl:text-lg p-header-fa opacity-header-icon cursor-pointer"
          [icon]="faSignOutAlt"></fa-icon>
      </a>
    </div>
  </div>
</div>

// apps/web/src/lib/components/settings/settings-header.svelte
<script lang="ts">
  import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons';
  import Fa from 'svelte-fa';
  import { pxScreen, translateXHeaderFa, opacityHeaderIcon, pHeaderFa } from '$lib/css-classes';

  export let leavePageLink: string;
</script>

<div class="relative h-12 bg-gray-700 text-white xl:h-10">
  <div class="flex h-full justify-end {pxScreen}">
    <div class="flex transform-gpu {translateXHeaderFa}">
      <a href={leavePageLink}>
        <span
          class="flex h-full items-center text-xl xl:text-lg {pHeaderFa} {opacityHeaderIcon} cursor-pointer"
        >
          <Fa icon={faSignOutAlt} />
        </span>
      </a>
    </div>
  </div>
</div>
