// src/app/book-manager/book-card/book-card.component.ts
/**
 * @license BSD-3-Clause
 * Copyright (c) 2021, ッツ Reader Authors
 * All rights reserved.
 */

import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { faImage } from '@fortawesome/free-regular-svg-icons';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'app-book-card',
  templateUrl: './book-card.component.html',
  styleUrls: ['./book-card.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BookCardComponent {
  @Input() imagePath?: string | Blob;

  @Input() title!: string;

  @Input() progress = 0;

  faImage = faImage;

  loadImageFail$ = new BehaviorSubject<boolean>(false);
}

<div class="relative cursor-pointer aspect-w-2 aspect-h-3">
  <span>
    <img *ngIf="imagePath && ((loadImageFail$ | async) === false); else imageNotFoundTemplate"
         class="w-full h-full object-cover"
         [src]="imagePath | imageResolver"
         (error)="loadImageFail$.next(true)"
         alt="">
    <ng-template #imageNotFoundTemplate>
      <fa-icon [icon]="faImage"
               class="w-full h-full flex justify-center items-center text-5xl sm:text-7xl dark:text-white">
      </fa-icon>
    </ng-template>
    <div class="absolute bottom-0 inset-x-0">
      <div class="bg-gray-800 bg-opacity-80 text-white text-justify text-sm p-0.5 px-1.5 h-16 sm:text-base sm:p-1.5 sm:h-21">
        <span class="line-clamp-3">{{ title }}</span>
      </div>
      <div class="h-2.5 bg-gray-400	bg-opacity-80">
        <div class="bg-gradient-to-b from-red-600 to-red-900 h-full rounded"
             [style.width]="(progress * 100) + '%'"></div>
      </div>
    </div>
  </span>
</div>

// apps/web/src/lib/components/book-card/book-card.svelte
<script lang="ts">
  import { faImage } from '@fortawesome/free-regular-svg-icons';
  import { onDestroy } from 'svelte';
  import Fa from 'svelte-fa';

  export let imagePath: string | Blob;
  export let title: string;
  export let progress: number;

  let objectUrl = '';

  onDestroy(() => {
    if (objectUrl) {
      URL.revokeObjectURL(objectUrl);
    }
  });

  function convertImagePath(value: string | Blob) {
    if (objectUrl) {
      URL.revokeObjectURL(objectUrl);
      objectUrl = '';
    }
    if (typeof value !== 'string') {
      objectUrl = URL.createObjectURL(value);
      return objectUrl;
    }

    return value;
  }

  function mapImagePathFactory() {
    let prevValue: string | Blob | undefined;
    let prevResponse: string | undefined;

    const isEqual = (newValue: string | Blob) => {
      if (!prevValue) return false;
      if (typeof prevValue !== 'object' || typeof newValue !== 'object') {
        return prevValue === newValue;
      }

      return prevValue.type === newValue.type && prevValue.size === newValue.size;
    };

    return (value: string | Blob) => {
      if (isEqual(value)) return prevResponse as string;

      prevValue = value;
      prevResponse = convertImagePath(value);

      return prevResponse;
    };
  }

  const mapImagePath = mapImagePathFactory();

  let imgEl: HTMLImageElement | undefined;
  let imageLoading = true;

  $: imageLoadComplete = imgEl?.complete && !imageLoading;
</script>

<div class="aspect-w-2 aspect-h-3 relative cursor-pointer" role="button" on:click>
  <div class="inline">
    <div class="h-full w-full text-5xl sm:text-7xl">
      {#if !imageLoadComplete}
        <Fa class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" icon={faImage} />
      {/if}

      {#if imagePath}
        <img
          src={mapImagePath(imagePath)}
          class="relative h-full w-full object-cover transition delay-150 duration-700 ease-out"
          bind:this={imgEl}
          class:blur={!imageLoadComplete}
          on:load={() => (imageLoading = false)}
          alt=""
          decoding="async"
        />
      {/if}
    </div>

    <div class="absolute inset-x-0 bottom-0">
      <div
        class="sm:h-21 h-16 bg-gray-800 bg-opacity-80 p-0.5 px-1.5 text-justify text-sm text-white sm:p-1.5 sm:text-base"
      >
        <span class="line-clamp-3">{title}</span>
      </div>
      <div class="h-2.5 bg-gray-400	bg-opacity-80">
        <div
          class="h-full rounded bg-gradient-to-b from-red-600 to-red-900"
          style:width="{progress * 100}%"
        />
      </div>
    </div>
  </div>
</div>
